### ISSUE TITLE
[General Bug] Wallpaper does not Switch on timer

### ISSUE THREAD

**Issue by Majurad** [aridevelopment-de/myanimetab#73]
**Describe the bug**
Wallpaper Switch Playlist Order type 'Shuffled' is not working as intended, unless When to switch is set to type 'Only on Page Visit'.
If you have any other 'When to switch' selected aside from 'Only on Page Visit', then the image will never switch. I have tested this on selections 10 seconds, every minute, 2 minutes, and 5 minutes, with all results the same. The image either continuously chooses the same one, or does not switch at all. I left it running overnight on a 10 second option with the same image showing the next day.

**To Reproduce**
1. Go to the settings
2. Choose any of the timed options for When to switch Wallpaper
3. Choose Shuffled Playlist Order
4. Wait whatever the set time limit is
5. The image will be the same.
6. optional wait the time again, and will still not change to a new image

**Expected behavior**

Once you wait the time limit that it is set to the wallpaper image should swap to any random image from your playlist.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Windows 10, Version 21H2, Build number 19044.1706
 - Browser: Firefox 
 - Version 100.0 (64-bit)

**Additional context**
My best guess is a typo or incorrect logic in the timed portion of the code for the shuffle call.

**Comment by Ari24-cb24** [comment]
Someone else already told me about that bug, but thanks for the issue. Can't say for sure when this will be fixed

**Comment by Ari24-cb24** [comment]
Fixed in the rewrite branch, will be merged and released soon
